name: docker-build

on:
  workflow_dispatch:
  push:
    paths-ignore:
      - 'docs/**'
      - 'README.md'
    branches:
      - 'main'
        # tags:
#      - 'v*'
# release:
#    types: [published]

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
        with:
          submodules: true

            #- name: Checkout submodules
            #  run: git submodule update --init --recursive

            # - name: Print path
            #   run: |
            #     ls
            #     file scanservjs
            #     ls scanservjs
            #     # echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}
          #
      - name: Set up QEMU for multi-platform build
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        
      - name: Login to DockerHub
        uses: docker/login-action@v2 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
        
      #- name: Push staging
      #  if: github.ref == 'refs/heads/staging'
      #  uses: docker/build-push-action@v2
      #  with:
      #    push: true
      #    tags: ${{ secrets.DOCKERHUB_USERNAME }}/scanservjs-hplip:staging
      #    target: scanservjs-hplip
      #    platforms: linux/amd64,linux/arm64,linux/arm/v7

      - name: Push master
        #if: github.ref == 'refs/heads/master-upstream'
        uses: docker/build-push-action@v3
        with:
          context: ./scanservjs
            # file: ./scanservjs/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/scanservjs-hplip:latest
          target: scanservjs-hplip
          platforms: linux/amd64,linux/arm64,linux/arm/v7

            # - name: Get version
            #   id: get_version
            #   if: startsWith(github.ref, 'refs/tags/v')
            #   run: |
            #     cd scanservjs
            #     echo $(git tag --points-at $(git rev-parse HEAD))
            #     echo ::set-output name=VERSION::git tag --points-at $(git rev-parse HEAD)
            #     # echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}

            # - name: Push release
            #   if: startsWith(${{ steps.get_version.outputs.VERSION }}, 'v')
            #   uses: docker/build-push-action@v2
            #   with:
            #     push: ${{ github.event_name != 'pull_request' }}
            #     tags: ${{ secrets.DOCKERHUB_USERNAME }}/scanservjs-hplip:release-${{ steps.get_version.outputs.VERSION }}
            #     target: scanservjs-hplip
            #     platforms: linux/amd64,linux/arm64,linux/arm/v7
